[문제-1] 길이가 10인 0-벡터를 만드세요.

In [2]:
import numpy as np

print(np.zeros(10, dtype=np.int32))

[0 0 0 0 0 0 0 0 0 0]


[문제-2] 길이가 10이며 다섯번째 원소만 1이고 나머지 원소는 모두 0인 벡터를 만드세요.

In [41]:
zeros = np.zeros(10, dtype='int')
zeros[4] = 1
print(zeros)

[0 0 0 0 1 0 0 0 0 0]


 [문제-3] 10 부터 49까지의 값을 가지는 벡터를 만드세요.

In [44]:
a = np.arange(10, 50)
print(a)
r = np.flip(a)
print(r)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


[문제-4] 위 벡터의 순서를 바꾸세요.

In [42]:
print(np.arange(10, 50)[::-1])
print(np.arange(49, 9, -1))

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


 [문제-5] 0부터 8까지의 값을 가지는 3x3 행렬을 만드세요.

In [8]:
print(np.arange(0, 9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


[문제-6] 벡터 [1,2,0,0,4,0] 에서 원소의 값이 0이 아닌 원소만 선택한 벡터를 만드세요.

In [45]:
vct = np.array([1,2,0,0,4,0])
print(vct[vct != 0])

[1 2 4]


 [문제-7] 3x3 단위 행렬(identity matrix)을 만드세요

In [11]:
print(np.identity(3, dtype='int'))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [46]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[문제-8] 난수 원소를 가지는 3x3 행렬을 만드세요

In [48]:
print(np.random.randint(0, 100, (3,3)))
print(np.random.rand(3,3))

[[84 21 84]
 [99 46 46]
 [45 94 84]]
[[0.15496401 0.45724876 0.96890676]
 [0.31390649 0.94511652 0.26973426]
 [0.04962017 0.63149658 0.37755995]]


[문제-9] 위에서 만든 난수 행렬에서 최대값/최솟값 원소를 찾으세요.

In [16]:
np.random.seed(10)
array1 = np.random.randint(0, 100, (3,3))
print(array1)
print(np.amax(array1))
print(np.amin(array1))

[[ 9 15 64]
 [28 89 93]
 [29  8 73]]
93
8


[문제-10] 위에서 만든 난수 행렬에서 행 평균, 열 평균을 계산하세요.

In [15]:
print(np.average(array1, axis=1))  # 행평균
print(np.average(array1, axis=0))  # 열평균

[29.33333333 70.         36.66666667]
[22.         37.33333333 76.66666667]


[문제-11] 5x5짜리 정방행렬의 단위행렬을 생성하시오

In [17]:
print(np.identity(5, dtype='int'))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


 [문제-12] 10~50까지 값 9개를 정수로 발생시켜 출력

In [18]:
randomArray = np.random.randint(10, 51, 9)
print(randomArray)

[10 50 46 26 46 21 34 43 18]


[문제-13] '문제-12' 배열의 shape을 3x3으로 변환

In [21]:
randomArray = randomArray.reshape(3,3)
print(randomArray)

[[10 50 46]
 [26 46 21]
 [34 43 18]]


 [문제-14] '문제-13' 배열의 각 행끼리의 합을 구하여 출력

In [49]:
print(np.sum(randomArray, axis=1))
print(randomArray.sum(axis=1))

[106  93  95]
[106  93  95]


[문제-15] '문제-13' 배열의 각 열 중 최대값 구하여 출력

In [23]:
print(np.amax(randomArray, axis=0))

[34 50 46]


[문제-16] '문제-13' 배열의 전체 요소의 평균을 구하여 출력

In [50]:
print(np.average(randomArray))
print(np.mean(randomArray))

32.666666666666664
32.666666666666664


 [문제-17] 1~10 사이의 정수를 요소로 하는 2x3 배열 생성

In [26]:
np.random.seed(10)
a = np.random.randint(1, 11, 6).reshape(2,3)  # (1, 11, (2,3))
print(a)

[[10  5  1]
 [ 2 10  1]]


 [문제-18] 10~20 사이의 정수를 요소로 하는 3x2 배열 생성

In [51]:
np.random.seed(10)
b = np.random.randint(10, 21, (3,2))
print(b)

[[19 14]
 [10 11]
 [19 10]]


 [문제-19] '문제-17'과 '문제-18'의 두 배열의 행렬 곱을 구하여 출력

In [30]:
x = np.matmul(a,b)  # a@b
print(x)

[[259 205]
 [157 148]]


[문제-20] '문제-19' 배열의 전치 행렬을 구하여 출력

In [31]:
print(x.T)  # np.transpose(x)

[[259 157]
 [205 148]]


[문제-21] 로또 번호 생성하기 (1~46 사이의 중복되지 않은 정수 6개 추출)

In [52]:
randnum = np.arange(1, 47)   # randint는 중복값도 발생시킴, 중복값도 뽑을 수 있음 
print(np.random.choice(randnum, 6, replace=False))

[21  4 46 18 32 36]
